name: Test Near Contract

on:
  pull_request:
    paths:
      - target_chains/near/**
      - wormhole_attester/sdk/rust/**
  push:
    branches:
      - main
    paths:
      - target_chains/near/**
      - wormhole_attester/sdk/rust/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: target_chains/near/receiver
    steps:
      - uses: actions/checkout@v2
      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Install Near Sandbox
        run: |
          mkdir /tmp/near-sandbox
          curl -LsSf https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Linux-x86_64/2.1.1/near-sandbox.tar.gz | tar zxf - -C /tmp/near-sandbox
      - name: Test
        run: NEAR_SANDBOX_BIN_PATH=/tmp/near-sandbox/Linux-x86_64/near-sandbox ./workspace-test.sh
